/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "secondary-container": "#90efef",
        "secondary-fixed-dim": "#76d6d5",
        "surface-container-lowest": "#ffffff",
        primary: "#001e40",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c3c6d1",
        "on-surface-variant": "#43474f",
        "tertiary-fixed-dim": "#66dd8b",
        "inverse-surface": "#2d3133",
        background: "#f7f9fb",
        "error-container": "#ffdad6",
        secondary: "#006a6a",
        surface: "#f7f9fb",
        "tertiary-fixed": "#83fba5",
        "inverse-primary": "#a7c8ff",
        "tertiary-container": "#003c1b",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001b3c",
        "on-surface": "#191c1e",
        "on-primary-container": "#799dd6",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#93f2f2",
        "primary-fixed": "#d5e3ff",
        "on-tertiary-fixed": "#00210c",
        "surface-dim": "#d8dadc",
        tertiary: "#00240e",
        "on-secondary": "#ffffff",
        "surface-tint": "#3a5f94",
        "on-secondary-fixed": "#002020",
        "surface-container": "#eceef0",
        "surface-variant": "#e0e3e5",
        "primary-container": "#003366",
        "on-tertiary-container": "#35b063",
        "on-tertiary-fixed-variant": "#005227",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#a7c8ff",
        "on-primary-fixed-variant": "#1f477b",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#006e6e",
        outline: "#737780",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#004f4f",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "sp-md": "24px",
        margin: "32px",
        "margin-mobile": "16px",
        "sp-xl": "64px",
        "container-max": "1280px",
        "sp-xs": "4px",
        "sp-sm": "12px",
        "sp-lg": "40px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
