# Weights applied for deterministic ranking formulas
WEIGHT_SPECIALIZATION_MATCH: float = 0.25
WEIGHT_TRUST_SCORE: float = 0.15
WEIGHT_DISTANCE: float = 0.15
WEIGHT_BILLING_TRANSPARENCY: float = 0.15
WEIGHT_DOCTOR_QUALITY: float = 0.10
WEIGHT_PATIENT_SATISFACTION: float = 0.10
WEIGHT_AFFORDABILITY: float = 0.10

# Default thresholds
MAX_RECOMMENDATIONS_COUNT: int = 5
DEFAULT_SEARCH_RADIUS_KM: int = 15

# Geospatial Constraints
EARTH_RADIUS_KM: float = 6371.0

# Medical Priority Mappings
URGENCY_LOW: str = "LOW"
URGENCY_MEDIUM: str = "MEDIUM"
URGENCY_HIGH: str = "HIGH"
URGENCY_CRITICAL: str = "CRITICAL"