from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field, field_validator

class BrowserLocation(BaseModel):
    city: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    formattedAddress: Optional[str] = None

class ContextRequest(BaseModel):
    conversation_id: str = Field(..., description="Unique conversation identifier")
    message: str = Field(..., description="User message text")
    browser_location: Optional[BrowserLocation] = Field(None, description="User browser location if available")

class ExtractedPatientContext(BaseModel):
    symptoms: Optional[List[str]] = Field(default_factory=list, description="List of reported symptoms")
    age: Optional[Union[int, str]] = Field(None, description="Patient age in years or string description")
    gender: Optional[str] = Field(None, description="Patient gender")
    duration: Optional[str] = Field(None, description="Symptom duration (e.g., '2 days', '1 week')")
    severity: Optional[str] = Field(None, description="Symptom severity (e.g., 'mild', 'moderate', 'severe')")
    medical_history: Optional[List[str]] = Field(default_factory=list, description="Existing medical history / conditions")
    current_medications: Optional[List[str]] = Field(default_factory=list, description="Current medications")
    allergies: Optional[List[str]] = Field(default_factory=list, description="Known allergies")
    emergency_flag: bool = Field(default=False, description="True if red-flag emergency symptoms detected")
    language: Optional[str] = Field(default="English", description="Primary communication language")
    additional_clinical_info: Optional[str] = Field(None, description="Any extra useful clinical information")
    browser_location: Optional[BrowserLocation] = Field(None, description="Browser location data")

    @field_validator('symptoms', 'medical_history', 'current_medications', 'allergies', mode='before')
    @classmethod
    def ensure_list(cls, v):
        if v is None:
            return []
        return v

class SufficiencyValidation(BaseModel):
    is_sufficient: bool = Field(..., description="True if sufficient clinical info exists for hospital discovery")
    missing_fields: List[str] = Field(default_factory=list, description="List of key clinical fields still missing")
    primary_missing_field: Optional[str] = Field(None, description="The single most important missing field to ask about first")
    reasoning: Optional[str] = Field(None, description="Clinical justification for sufficiency status")

class ContextFollowUpResponse(BaseModel):
    status: str = Field("FOLLOW_UP", description="Status indicator")
    question: str = Field(..., description="Follow-up question generated by Mistral")
    missing_fields: List[str] = Field(default_factory=list, description="Missing required fields")
    extracted_context: Optional[Dict[str, Any]] = Field(None, description="Extracted clinical signals accumulated so far")

class ContextCompleteResponse(BaseModel):
    status: str = Field("COMPLETE", description="Status indicator")
    context: Dict[str, Any] = Field(..., description="Complete patient context object")

class ConversationState(BaseModel):
    conversation_id: str
    chat_history: List[Dict[str, str]] = Field(default_factory=list)
    structured_context: Dict[str, Any] = Field(default_factory=dict)
    missing_fields: List[str] = Field(default_factory=list)
    last_updated: Optional[str] = None
