name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch: # This adds a manual "Run Workflow" button in GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Webhook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"